version: '3'
services:
  api:
    build: ./backend
    container_name: 'backend-api'
    ports:
      - 8000:8000
    volumes:
      - './backend:/backend'
    env_file:
      - backend/api/.env
  frontend:
    build: ./frontEnd
    container_name: 'frontend'
    ports:
      - 3000:3000
    volumes:
      - './frontEnd:/app'
    command: npm start
    stdin_open: true
    environment:
       - CHOKIDAR_USEPOLLING=true
  

